version: '3.3'

services:
  postgres:
    image: postgres
    container_name: alexa-rpg
    networks:
      - alexa-rpg-network
    environment:
      POSTGRES_PASSWORD: uXAPlTPNR2vw1
      POSTGRES_DB: alexa-rpg-dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  alexa-rpg-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexa-rpg-app
    networks:
      - alexa-rpg-network 
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: 'production'
      APP_NAME: 'alexa_rpg'
      DEBUG: 'false'
      PORT: '3000'

      DATABASE_HOST: 'alexa-rpg'
      DATABASE_NAME: 'alexa-rpg-dev'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'uXAPlTPNR2vw1'
      DATABASE_PORT: '5432'
    
    depends_on:
      - postgres

networks:
  alexa-rpg-network:
    driver: bridge

